name: ms-gen-cu121
channels:
- pytorch
- dglteam/label/th24_cu121
- conda-forge
- pyg
- bioconda
dependencies:
- python=3.10.*
- cython
- ray-tune
- matplotlib=3.4.*
- rdkit=2021.03.*
- conda-forge::python-graphviz
- conda-forge::pygraphviz
- pip=21.2.*
- ipykernel
- einops
- nb_conda_kernels=2.3.*
- seaborn=0.11.*
- MKL=2024.0.0
- dgl
