#python launcher_scripts/run_from_config.py configs/iceberg/dag_inten_train_canopus.yaml
#python launcher_scripts/run_from_config.py configs/iceberg/dag_inten_train_nist.yaml
python launcher_scripts/run_from_config.py configs/iceberg/dag_inten_train_msg_allev_entropy.yaml
python launcher_scripts/run_from_config.py configs/iceberg/dag_inten_train_msg_allev_cosine.yaml

# contrastive finetune
#python launcher_scripts/run_from_config.py configs/iceberg/dag_inten_contr_finetune_nist.yaml
